version: "3.9"
services:
  openfisca:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/app
    command: make serve-local
    user: user:user
    ports:
      - 50000:50000
    networks:
      - openfisca
  dashboard:
    build:
      context: ./dashboard
      dockerfile: ./Dockerfile
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/dashboard/src:/app/src
    environment:
      - YADOKARI_GTM_ID=${YADOKARI_GTM_ID:-GTM-596RJQDP} # Google Tag Manager ID（OS環境変数が設定されていない場合は開発用のGoogle Tag Manager IDが設定される）
    #command: npm run dev
    #user: user:user
    ports:
      - 30000:30000
    networks:
      - openfisca
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.3.0
    environment:
      API_URL: http://localhost:50000/spec
    ports: 
      - 8080:8080
    depends_on:
      - openfisca
    networks:
      - openfisca

networks:
  openfisca:
    name: openfisca
